# Einstein Summation in Numpy

In [1]:
# Import dependencies.
import numpy as np

### Control the printing precision

In [2]:
from __future__ import print_function

# customize buil_in print() function for setting floating point printing precision.
def print(*args):
    __builtins__.print( *("%.4f" % a if isinstance(a, float) else a for a in args) )

In [3]:
# # to print each floating point number with just four decimal places.
# np.set_printoptions( precision = 4, floatmode = 'fixed' ) 

# # magic command for precision
# %precision 4

## What is einstein summation ?

## All in One !

### Scalar product of two scalars

In [4]:
# Creating two scalars
a = np.random.uniform(0, 10) 
b = np.random.uniform(0, 10)

print('Inputs')
print(a, '\t', b)

# einsum() for scalar product of two scalars.
c = np.einsum( ' ,  -> ' , a , b )

print('\n Output')
print(c)

Inputs
8.70317208582332 	 0.10770224511151838

 Output
0.9373511732350679


### Scalar product of a vector with a scalar.

In [5]:
# Creating one vector and a scalar.
a = np.random.uniform(0, 10, (5)) 
b = np.random.uniform(0, 10)

print('Inputs')
print(a, '\t', b)

# einsum() for scalar product of a vector with a scalar.
c = np.einsum( ' i , -> i' , a , b )

print('\n Output')
print(c)

Inputs
[0.26364026 6.22436457 4.94399381 2.54848619 5.30700906] 	 8.291959736680154

 Output
[ 2.18609438 51.6121804  40.9953976  21.13194489 44.00550543]


### Inner product of two vectors

In [16]:
# Creating one vector and a scalar.
a = np.random.uniform(0, 10, (5)) 
b = np.random.uniform(0, 10, (5))

print('Inputs')
print(a, '\t', b)

# einsum() for Inner product of two vector.
c1 = np.einsum( ' i , i ->  ' , a , b )



print('\n Output')
print(c1, '\n')
print(c2, '\n')

Inputs
[8.26274076 3.38162913 3.58372194 1.5146837  0.1156425 ] 	 [8.45952971 5.18367192 3.67642627 2.15841577 1.31679474]

 Output
104.02504102228008 

[69.89890095 17.52925597 13.17528948  3.26931718  0.15227744] 



### Element-wise product of two vectors

In [20]:
a = np.random.uniform(0, 10, (5)) 
b = np.random.uniform(0, 10, (5))

print('Inputs')
print(a, '\t', b)

# einsum() for Inner product of two vector.
c1 = np.einsum( ' i , i -> i ' , a , b )

print('\n Output')
print(c1, '\n')

Inputs
[7.39537862 4.89485567 6.56359937 8.74455623 7.74195933] 	 [6.94050203 4.74829796 0.56633115 6.22351673 8.19228727]

 Output
[51.32764032 23.24223315  3.71717079 54.42189203 63.42435487] 



### Outer product of two vectors.

In [21]:
# Creating one vector and a scalar.
a = np.random.uniform(0, 10, (3)) 
b = np.random.uniform(0, 10, (3))

print('Inputs')
print(a, '\t', b)

# einsum() for outer product of two vector.
c = np.einsum( ' i , j -> ij ' , a , b )

print('\n Output')
print(c)

Inputs
[6.96160511 8.38371757 0.34854067] 	 [3.58356088 6.87355032 6.38291976]

 Output
[[24.94733576 47.85094303 44.43536681]
 [30.04356231 57.62590452 53.51259648]
 [ 1.2490167   2.39571182  2.22470712]]


### Matrix Multiplication  

In [23]:
A = np.random.randint(0, 10, (4,3))
B = np.random.randint(0, 10, (3,3))
print(A.shape, '\t', B.shape)

print('\n Inputs')
print(A, '\n\n', B)

# einsum() for outer product of two vector.
C = np.einsum( ' ik , kj -> ij ' , A , B )

print('\n Output')
print(C , '\n')
print("Order of resultant Matrix is:", C.shape)

(4, 3) 	 (3, 3)

 Inputs
[[9 4 5]
 [0 1 3]
 [2 6 1]
 [7 2 9]] 

 [[9 5 6]
 [7 6 2]
 [8 9 1]]

 Output
[[149 114  67]
 [ 31  33   5]
 [ 68  55  25]
 [149 128  55]] 

Order of resultant Matrix is: (4, 3)


## Quadratic products

In [24]:
x = np.random.randint(0, 10, (4))
A = np.random.randint(0, 10, (4,3))
y = np.random.randint(0, 10, (3))

print('\n Inputs')
print(x, '\n\n', A, '\n\n', y)

# einsum() for computing x.T * A * y and output is a scalar.
C = np.einsum( ' i, ij, j -> ' , x, A, y )

print('\n Output')
print(C)


 Inputs
[7 9 5 1] 

 [[2 6 7]
 [6 0 8]
 [4 5 1]
 [2 0 2]] 

 [9 4 9]

 Output
2230


### Matrix (2D - Array) transpose

In [25]:
A = np.random.randint(0, 10, (2,3))

print('\n Input')
print('Input shape is ', A.shape, '\n\n', A)

# einsum() for computingx.T * A * y and output is a scalar.
C = np.einsum( ' ij -> ji ' , A )

print('\n Output')
print('Output shape is ', C.shape, '\n\n', C )


 Input
Input shape is  (2, 3) 

 [[2 0 1]
 [3 4 7]]

 Output
Output shape is  (3, 2) 

 [[2 3]
 [0 4]
 [1 7]]


### Tensor(3D/4D-Array) Transpose

In [27]:
# Make random inputs
np_RGB_images = np.random.randint(0, 10, (16, 300, 200, 3)) # shape is (B, H, W, C)

print('Input shape is  ', np_RGB_images.shape)

T1 = np.einsum( 'ijmn -> injm',  np_RGB_images )   # Output shape is (B, C, H, W)
T2 = np.einsum( 'ijmn -> jmni',  np_RGB_images )   # Output shape is (H, W, C, B)
T3 = np.einsum( 'ijmn -> imjn',  np_RGB_images )   # Output shape is (B, W, H, C)
T4 = np.einsum( 'ijmn -> inmj',  np_RGB_images )   # Output shape is (B, C, W, H)

print('\n Output shapes are:\n')
print(T1.shape ,'\t just like images in pytorch.', '\n'  , T2.shape,   '\n', T3.shape, '\n', T4.shape, '\n')
print(" PS: You can do as many permutations of axis you want !!! ")

Input shape is   (16, 300, 200, 3)

 Output shapes are:

(16, 3, 300, 200) 	 just like images in pytorch. 
 (300, 200, 3, 16) 
 (16, 200, 300, 3) 
 (16, 3, 200, 300) 

 PS: You can do as many permutations of axis you want !!! 
